# Generated by Django 3.2 on 2021-04-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('product_number', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('product_shipping_method', models.CharField(blank=True, choices=[('LOCAL_SHIPPING', 'LOCAL_SHIPPING'), ('LOGISITC_COMPANY', 'LOGISITC_COMPANY'), ('PICKUP', 'PICKUP')], max_length=128, null=True, verbose_name='product_shipping_method')),
                ('status', models.CharField(blank=True, choices=[('OFS', 'OFS'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DECLINED', 'DECLINED'), ('SOLD', 'SOLD')], default='PENDING', max_length=128, null=True, verbose_name='status')),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_refundable', models.BooleanField(default=False, verbose_name='is_refundable')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
