"""
Django settings for django_boilerplate project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import sys
from os import path

env = environ.Env()
environ.Env.read_env(str(".env"))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, path.join(BASE_DIR, 'apps'))
#APP_DIR = str(BASE_DIR) + '/django_boilerplate'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'django.contrib.sites',
    'social_django',
]

#Local apps
INSTALLED_APPS += [
    'api',
	'website',

	'rest_framework.authtoken',
    'rest_auth',

    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.apple',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'django_boilerplate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_boilerplate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'socialmedia',
        'USER': 'postgres',
        'HOST': 'localhost',
        'PASSWORD': 'admin',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.apple.AppleIdAuth',
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = path.join(BASE_DIR, 'static').replace('\\', '/')
STATIC_URL = '/static/'
# STATIC_ROOT = str(BASE_DIR)  "static")
# STATICFILES_DIRS = [(str(APP_DIR)+ "/static")]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MEDIA_ROOT = (str(BASE_DIR)+ "/media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        'rest_framework.authentication.BasicAuthentication',
    ),
}


CRISPY_TEMPLATE_PACK = 'bootstrap4'
AUTH_USER_MODEL = 'api.User'
# =============== FACEBOOK =============== 
# My
SOCIAL_AUTH_FACEBOOK_KEY = '289765542840643'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '56e91e5eee1c78fe0469e8bee41574e4'  # App Secret

# Rachit
# SOCIAL_AUTH_FACEBOOK_KEY = '1668463020029321'  # App ID
# SOCIAL_AUTH_FACEBOOK_SECRET = '6ac0e34f9fe685db23eee0c50babcd98'  # App Secret
# ACCESSTOKEN => EAAXtdVGhNYkBAF4bsuZAuez0HzTYgF2S3HxQcLwyZCpsUz5zCPHRg8oTmxg9dG3hDVJbbd17XCo1uZAQfFZB2kdBjIEwjuazn8JUXZB3x73ZAFDsFkPJQvSY1K4Bu6ZBBFZBfYPBTo49dSxC4h8MA14BTZBZBPLn9XWuGSFufqpOjaDFJ9GREP7Wg7AyEUlrlENQkKjQDsQkEyDFE4CozeUA1ovxDmxrglJcV9edzZAQwJR5QZDZD

# =============== GOOGLE =============== 
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '563987567432-e1v2f1rrdrgtpsm6mbgp6mff9tjiqqpd.apps.googleusercontent.com'  # App ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'wjAZAmmhfqPVJpe3j-sTVwIF'  # App Secret

# =============== TWITTER =============== 
SOCIAL_AUTH_TWITTER_KEY = "zdJcHdoxwNs0T5KZ4r2Ynqeik" # App ID
SOCIAL_AUTH_TWITTER_SECRET = "dJxT4LnsbrNFKDKjh7nMtbJSecvinRgPmEP5q7WHIDHNBOzgwa" # App Secret

# =============== APPLE =============== 
SOCIAL_AUTH_APPLE_ID_CLIENT = 'com.mediyoga'             # Your client_id com.application.your, aka "Service ID"
SOCIAL_AUTH_APPLE_ID_TEAM = 'CPCQ32Z2TQ'               # Your Team ID, ie K2232113
SOCIAL_AUTH_APPLE_ID_KEY = 'L53YS3ALGA'                # Your Key ID, ie Y2P99J3N81K
SOCIAL_AUTH_APPLE_ID_SECRET = "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm05jjbNmcrTIOFwOOHf3v0f+90wQoYu+CIhcP5YDcGagCgYIKoZIzj0DAQehRANCAATzyV5vs91FGN3p4J3xHq3kFmyG+s/JmSJsNxDg+4VYpbJNJSU4mxfKgVAGStM4t2jujxQ1jqIvwO927sKVqyT7"


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'home'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/'