# Generated by Django 3.2 on 2021-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_boilerplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
