# Generated by Django 3.2 on 2021-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_website', '0003_auto_20210520_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_number_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_link_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
