# Generated by Django 3.2 on 2021-04-20 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=128)),
                ('blog', models.TextField(max_length=200)),
                ('publish', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 35, 44, 640591))),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
