# Generated by Django 3.2 on 2021-04-22 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210420_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 10, 10, 17, 405844)),
        ),
    ]
