# Generated by Django 3.2 on 2021-04-28 04:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210428_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 28, 9, 53, 34, 587713)),
        ),
    ]
