# Generated by Django 3.2 on 2021-04-28 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210428_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keyword',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 28, 9, 57, 46, 98350)),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
