# Generated by Django 3.2 on 2021-04-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(blank=True, default='', help_text='Notification Title', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Notification Description', null=True, verbose_name='Description')),
                ('is_read', models.BooleanField(default=False, help_text='Is Notification Read?', verbose_name='Is Notification Read?')),
                ('notification_type', models.CharField(blank=True, choices=[('OTHER', 'OTHER'), ('BOOKING', 'BOOKING')], help_text='Notification Title', max_length=255, null=True, verbose_name='Title')),
                ('profile_image', models.ImageField(blank=True, default='sample.jpg', null=True, upload_to='profile_image', verbose_name='Profile Image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
