# Generated by Django 3.2 on 2021-04-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_group_groupuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group User', 'verbose_name_plural': 'Group Users'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
