# Generated by Django 3.2 on 2021-04-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20210422_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
