# Generated by Django 3.2 on 2021-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20210427_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='User')),
                ('notification', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Notification')),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Notification Read?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_singleuser',
            field=models.BooleanField(default=False, verbose_name='Is Single User?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
