# Generated by Django 3.2 on 2021-05-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20210505_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.groupuser'),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
