# Generated by Django 3.2 on 2021-05-14 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0012_auto_20210514_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='user',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
