# Generated by Django 3.2 on 2021-05-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0013_auto_20210514_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='user',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
