# Generated by Django 3.2 on 2021-05-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210519_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.usercard'),
        ),
    ]
