# Generated by Django 3.2 on 2021-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210520_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
