from .category_list import CategoryListView, CategoryDataTablesAjaxPagination
from .add_category import CategoryAddView
from .edit_category import CategoryEditView
from .delete_category import CategoryDeleteView

from .subcategory.subcategory_list import SubCategoryListView, SubCategoryDataTablesAjaxPagination
from .subcategory.add_subcategory import SubCategoryAddView
from .subcategory.edit_subcategory import SubCategoryEditView
from .subcategory.delete_subcategory import SubCategoryDeleteView