# Generated by Django 3.2 on 2021-05-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_auto_20210427_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
