# Generated by Django 3.2 on 2021-05-26 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customadmin', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=222, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_plan', to='customadmin.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=222, null=True)),
                ('ordre_status', models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=222, null=True)),
                ('plan_status', models.CharField(blank=True, choices=[('active', 'Active'), ('cancel', 'Cancel')], max_length=222, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=222, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionorder_plan', to='customadmin.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionorder_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscriptions',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
