# Generated by Django 3.2 on 2021-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('category', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='MediaCategory')),
            ],
            options={
                'verbose_name': 'MediaCategory',
                'verbose_name_plural': 'MediaCategories',
                'ordering': ['-created_at'],
            },
        ),
    ]
