# Generated by Django 3.2 on 2021-05-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacategory_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('video', models.FileField(blank=True, null=True, upload_to='Videos', verbose_name='Video')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediacategory_api.mediacategory')),
            ],
            options={
                'verbose_name': 'MediaVideo',
                'verbose_name_plural': 'MediaVideos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediacategory_api.mediacategory')),
            ],
            options={
                'verbose_name': 'MediaImage',
                'verbose_name_plural': 'MediaImages',
                'ordering': ['-created_at'],
            },
        ),
    ]
